name: Pull dags to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST}}
          username: ${{ secrets.SERVER_USERNAME }}
          passphrase: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.XPATH }}
            ls
            rm -rf airfow_llm_layer
            git clone https://github.com/orai-ailab/airfow_llm_layer.git
            ls
            cd airfow_llm_layer
            echo "NODE_ENV=production" > .env
            echo "CENTIC_API_KEY=${{ secrets.CENTIC_API_KEY }}" > .env
            echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> .env
            echo "TOKEN_LUNAR=${{ secrets.TOKEN_LUNAR }}" >> .env
            echo "TOKEN_DISCORD=${{ secrets.TOKEN_DISCORD }}" >> .env
            echo "CHANNEL_ID=${{ secrets.CHANNEL_ID }}" >> .env
            echo "ES_NAME=${{ secrets.ES_NAME }}" >> .env
            echo "ES_PASSWORD=${{ secrets.ES_PASSWORD }}" >> .env
            echo "ES_HOST=${{ secrets.ES_HOST }}" >> .env
            echo "ES_PORT=${{ secrets.ES_PORT }}" >> .env


  