name: Deploy to Server

on:
  push:
    branches:
      - main # Thay thế bằng tên branch của bạn

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST}}
          username: ${{ secrets.SERVER_USERNAME }}
          passphrase: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.XPATH }}
            git pull

            rm -rf .env
            echo "NODE_ENV=production" > .env
            echo "CENTIC_API_KEY=${{ secrets.CENTIC_API_KEY }}" > .env
            echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> .env
            echo "TOKEN_LUNAR=${{ secrets.TOKEN_LUNAR }}" >> .env

  